---
language: python
python: 2.7
cache: pip
sudo: required

env:
  - TEST_RUN="./tests/test-flake8.sh"
  - TEST_RUN="./tests/test-shellcheck.sh"
  - TEST_RUN="./tests/test-yamllint.sh"

before_install:
  - pip install -U -r test-requirements.txt

install:
  - "./scripts/install.sh"
  - "./scripts/ibmcloud_auth.sh"

script: "$TEST_RUN"

deploy:
  provider: script
  script: "bx app push HelloWorld"
