---
language: python
python: 2.7
cache: pip
sudo: required

before_install:
  - pip install -U -r test-requirements.txt

install:
  - "./scripts/install.sh"
  - "./scripts/ibmcloud_auth.sh"

script:
  - "./tests/test-flake8.sh"
  - "./tests/test-shellcheck.sh"
  - "./tests/test-yamllint.sh"

deploy:
  provider: script
  script: "bx app push HelloWorld"
